### PR TITLE
Improvements

### PR DESCRIPTION
**Pull request by uwburn**
Hello,
thanks for your package, it's helping me in my projects!

While using it i experimented with a few improvements:

-  Use `debug` package instead of `console.log` to alert about errors while contacting Graylog, so that `stdout` it's not polluted
-  Correct structuring of the payload (include protocol version, use full message for multilines, destructure additional parameters, so that Graylog can support queries on them)
-  Enable HTTP socket keep alive, so that sockets are reused when possible
-  Add keepalive and timeout options for TCP (i don't think they were supported with the protocol options object)
- Small code improvments

Hope this helps improving the package.

### CODE REVIEW

**Comment by Buzut** [comment]
Hi Michele!

Thank you for your interest in the package and for your great code improvements.
Would you update the README to reflect the new options you've introduced (keep alive and timeout)?

Thanking you again.

**Comment by Buzut** [comment]
Thank you very much for these great improvements!

**Comment by uwburn** [comment]
Hello, i haven't replied yet as i've been super busy at work lately... the changes should be ok, but i didn't had time to test them, i will do ASAP.

Cheers!

**Comment by Buzut** [comment]
Hi Michele,
It seemed good to me so I merged it already. But I'll wait for your tests results before pushing it to npm.

You let me know.
Cheers!

**Comment by uwburn** [comment]
Tested, working as expected.

**Comment by Buzut** [comment]
Published!

**Pull request merged**
